baseURL = "https://ziiiliu.github.io/"  #"https://zl413.user.srcf.net/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Ziyi Liu"

# Change the default theme to be use when building the site with Hugo
theme = "Feelit"
themesDir = './themes'
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[author]
  name = "Ziyi"

[params]
  version = "1.0.X"
  description = "Ziii's Page"
  defaultTheme = "auto"
  gitRepo = "https://github.com/ziiiliu/ziiiliu.github.io"
  [params.home]
    [params.home.profile]
      enable = true
      title = "<h1>Ziyi Liu</h1>"
      subtitle = "Ziiiiiiiiiiiiiiiiiiiiii"
      avatarURL = "/images/profile.jpg"
      typeit = true
      social = true
      
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
  [params.social]
    github = "ziiiliu"
    LinkedIn = "zi-liu"
    Email = "zliu0629@gmail.com"
  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1
  [params.page]
    fontawesome = true
    cdnfontawesome = true
    twemoji = true
  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    author = true
    since = 2019
  [params.page.toc]
    enable=true
    auto=false
  [params.page.comment]
    enable=true  



[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    title = ""
    weight = 4 
    [[menu.main]]
    identifier = "newsletter"
    pre = ""
    post = ""
    name = "Newsletter"
    url = "/newsletter/"
    title = ""
    weight = 5  
    [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About Me"
    url = "/about/"
    title = ""
    weight = 6


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false